In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [22]:
a = tf.constant([[1,2], [3,4]])
b = tf.constant([[-1,3], [4,2]])

In [23]:
multiplicacao = tf.matmul(a,b)

In [26]:
with tf.Session() as sess:
  print(sess.run(a))
  print('\n')
  print(sess.run(b))
  print('\n')
  print(sess.run(multiplicacao))

[[1 2]
 [3 4]]


[[-1  3]
 [ 4  2]]


[[ 7  7]
 [13 17]]


In [27]:
multiplicacao2 = tf.matmul(b,a)

In [28]:
with tf.Session() as sess:
  print(sess.run(multiplicacao2))

[[ 8 10]
 [10 16]]


In [29]:
a2  = tf.constant([[2,3],[0,1],[-1,4]], name = 'a2')
b2  = tf.constant([[1,2,3],[-2,0,4]], name = 'b2')

In [31]:
multiplicacao3 =tf.matmul(a2,b2)

In [32]:
with tf.Session() as sess:
  print(sess.run(a2))
  print('\n')
  print(sess.run(b2))
  print('\n')
  print(sess.run(multiplicacao3))

[[ 2  3]
 [ 0  1]
 [-1  4]]


[[ 1  2  3]
 [-2  0  4]]


[[-4  4 18]
 [-2  0  4]
 [-9 -2 13]]
