In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
a = tf.constant([9,8,7], name = 'a')
b = tf.constant([1,3,2], name = 'b')

In [3]:
soma = a + b

In [4]:
type(a)

tensorflow.python.framework.ops.Tensor

In [5]:
print(a)

Tensor("a:0", shape=(3,), dtype=int32)


In [7]:
with tf.Session() as sess:
  print(sess.run(soma))

[10 11  9]


In [13]:
a1  = tf.constant([[1,2,3],[4,5,6]], name = 'a1')

In [14]:
type(a1)

tensorflow.python.framework.ops.Tensor

In [15]:
a1.shape

TensorShape([Dimension(2), Dimension(3)])

In [16]:
b1  = tf.constant([[1,2,3],[4,5,6]], name = 'b1')

In [17]:
soma1 = tf.add(a1, b1)

In [18]:
with tf.Session() as sess:
  print(sess.run(soma1))

[[ 2  4  6]
 [ 8 10 12]]


In [19]:
a2  = tf.constant([[1,2,3],[4,5,6]], name = 'a2')
b2  = tf.constant([[1],[2]], name = 'b2')

In [20]:
soma2 = tf.add(a2, b2)

In [21]:
with tf.Session() as sess:
  print(sess.run(soma2))

[[2 3 4]
 [6 7 8]]
