In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [10]:
p = tf.placeholder('float', None)

In [11]:
operacao = p + 2

In [12]:
with tf.Session() as sess:
  #sess.run(operacao)
  resultado = sess.run(operacao, feed_dict = {p:[1,2,3]})
  print(resultado)

[3. 4. 5.]


In [16]:
p2 = tf.placeholder('float', [None,5])
operacao2 = p2 + 5

In [15]:
with tf.Session() as sess:
  dados = [[1,2,3,4,5], [6,7,8,9,10]]
  resultado = sess.run(operacao2, feed_dict = {p2: dados})
  print(resultado)

[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
